### ISSUE TITLE
Add Tofino support

### ISSUE THREAD

**Issue by RandyLevensalor** [cablelabs/transparent-security#144]
Get working with simulators using the same code base with #ifdef compile-time directives.

Then run on real hardware.

**Comment by spisarski** [comment]
Just revived old tofino build and setup scripts and fixed p4 build for p4runtime (p4 code will probably not work correctly on tofino currently) in PR #163.
This effort will fix switchd and sdn with p4runtime or bfruntime.
The addition creation of integration tests will follow.

**Comment by spisarski** [comment]
Keeping this ticket open as more of an epic from which we can create other tickets around Tofino support

**Comment by spisarski** [comment]
This was basically an epic task and we are pretty much now all are or can perform our work on Tofino
