### ISSUE TITLE
Create CI job for running integration tests against core_tna.p4

### ISSUE THREAD

**Issue by spisarski** [cablelabs/transparent-security#264]
Create Jenkins job just like the one for tofino-aggregate

**Comment by spisarski** [comment]
@bo-quan - Please see the following issue when terraform is trying to init. Showing that the system is out of "space":

[ec2-user@ip-10-146-10-85 tofino]$ /var/lib/jenkins/workspace/terraform init

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "aws" (hashicorp/aws) 3.11.0...

Error installing provider "aws": write /tmp/getter873061035/archive: no space left on device.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occurred.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/linux_amd64


Error: write /tmp/getter873061035/archive: no space left on device


[ec2-user@ip-10-146-10-85 tofino]$ pwd
/var/lib/jenkins/workspace/transparent-security-tofino-lab-trial/automation/p4/tofino
[ec2-user@ip-10-146-10-85 tofino]$ df
Filesystem     1K-blocks    Used Available Use% Mounted on
devtmpfs         4033716      68   4033648   1% /dev
tmpfs            4044372     136   4044236   1% /dev/shm
/dev/nvme0n1p1   8189348 8084012      5088 100% /

**Comment by bo-quan** [comment]
Terraform seems to be leaving some big garbage which needs to be periodically cleaned up. I used the following commands on the jenkins server to release a lot of spaces (run from /var/lib/jenkins/workspace):

rm -rf ./transparent-security-*@2
and 
rm -rf ./transparent-security-*@3

After some clean up, the root partition was down from 99% to 72%:
/dev/nvme0n1p1   8189348 5752044   2337056  72% /
