### ISSUE TITLE
Activate tofino-build CI job on Jenkins

### ISSUE THREAD

**Issue by spisarski** [cablelabs/transparent-security#275]
Activate and test the existing job for building tofino AMIs

**Comment by spisarski** [comment]
@bo-quan - Can you upgrade the latest python version available? It appears that the job in question is failing now that we are trying to leverage python3 exclusively with TPS.

**Comment by bo-quan** [comment]
We haven't upgrade Jenkins for almost a year, let me upgrade Jenkins first, then python/pip/ansible.

**Comment by bo-quan** [comment]
Upgraded Jenkins from 2.187 to 2.263, and relevant plugins. Will take another snapshot and then upgrade python/pip3/ansible.

**Comment by bo-quan** [comment]
Upgraded to python3.6, ansible 2.10:

[ec2-user@ip-10-146-10-85 ~]$ python --version
Python 3.6.12
[ec2-user@ip-10-146-10-85 ~]$ ansible --version
ansible 2.10.2
  config file = None
  configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.12 (default, Aug 31 2020, 18:56:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
[ec2-user@ip-10-146-10-85 ~]$ pip --version
pip 9.0.3 from /usr/lib/python3.6/dist-packages (python 3.6)

**Comment by spisarski** [comment]
Something at the end of the job is causing it to report failure when it actually succeeded.

**Comment by spisarski** [comment]
First CI job completion: http://10.146.10.85:8080/job/transparent-security-env-build-tofino/153/console
