### ISSUE TITLE
Validate Ansible yml file ci

### ISSUE THREAD

**Issue by RandyLevensalor** [cablelabs/transparent-security#28]
Check the ansible playbooks are formatted correctly and don't have syntax errors.

https://github.com/ansible/ansible-lint

**Comment by spisarski** [comment]
One way to do this is to execute the ansible-playbook command with --check prior to running it for real

**Comment by spisarski** [comment]
Just installed ansible-lint on the Jenkins master
sudo pip install ansible-lint
