### ISSUE TITLE
Fix webhooks to Github for TPS CI jobs

### ISSUE THREAD

**Issue by spisarski** [cablelabs/transparent-security#327]
Github stopped accepting user/pass auth for webhooks and now only support tokens, therefore, we need to reconfigure them on Jenkins. see https://developer.github.com/changes/2020-02-14-deprecating-password-auth/

**Comment by snapsci** [comment]
Converted Jenkins CI jobs to use personal access token created by snapsci user, which fixed the CI issue (see http://10.146.10.85:8080/job/transparent-security-env-build-tofino/196/console)

**Comment by bo-quan** [comment]
Looking at the build triggering issue with comments

**Comment by bo-quan** [comment]
@spisarski or @Sanjhana-Jayagopal I think I fixed the triggering issue as I was able to trigger http://snapsci.cablelabs.com:8080/job/snaps-k8s/2782/ with comments. Could you create a dummy TS PR tomorrow to see if the issue is fixed for TS?

**Comment by spisarski** [comment]
@bo-quan - I just created a real one and they've kicked off, thanks!
