### ISSUE TITLE
Add support for TCP shim per INT spec

### ISSUE THREAD

**Issue by RandyLevensalor** [cablelabs/transparent-security#86]
If a packet is TCP, use the TCP shim without modifying the diffserv bit.

**Comment by spisarski** [comment]
Closed by accident; however, this appears to be obsolete with the UDP encapsulation changes.

**Comment by spisarski** [comment]
@RandyLevensalor - Please review and let us know if it is still valid.

**Comment by spisarski** [comment]
Obsolete...
